package hr.hrg.dialog.logback;

import javax.annotation.concurrent.NotThreadSafe;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;

import ch.qos.logback.classic.spi.StackTraceElementProxy;
import hr.hrg.dialog.core.*;
import org.slf4j.event.KeyValuePair;

import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.util.RawValue;

import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.spi.IThrowableProxy;

/// Reusable JSON log event writer used internally.
///
/// It tries to minimize allocations
/// - if add-opens available, uses direct string data access to avoid allocating byte[] for each string
/// - holds byte[] for common keys, to again avoid allocation byte[] caused by writing string in Java
/// - delegates custom key/value and MDC to jackson
/// - writes stack trace into JSON with optimized low allocation code
///
@NotThreadSafe
public class JsonLogWriter {

    /** Newline bytes (UTF-8) - strictly Unix LF (\n). */
    public static final byte[] NL = new byte[]{ 0x0A };

    /**
     * A value whose JSON representation has already been computed and encoded
     * to UTF-8 bytes.
     *
     * <p>This is a <b>trusted passthrough</b>: the bytes are injected into the
     * output stream verbatim — no escaping, no quoting, no validation. The
     * caller owns correctness of the payload; malformed content will corrupt
     * the surrounding JSON object.
     *
     * <p>Use it for values that are serialized once and reused across many
     * events, so the per-event cost is a single bulk byte copy instead of a
     * re-serialization. Example — a large, rarely-changing configuration or
     * metrics snapshot cached as pre-encoded bytes:
     *
     * <pre>{@code
     * // computed once, reused across many log lines
     * byte[] snapshotJson = mapper.writeValueAsBytes(configSnapshot);
     * ...
     * List.of(new KeyValuePair("config", new JsonLogWriter.RawJsonBytes(snapshotJson)))
     * }</pre>
     *
     * @param bytes the pre-encoded JSON fragment, written verbatim
     */
    public record RawJsonBytes(byte[] bytes){}

    private static final StringByteExtractor.ByteWriter STRING_STRATEGY = StringByteExtractor.getStrategy();

    // timestamp field ts includes starting { for object, and is generated by CodeBuddy StrPacker from project-automation
    // @CB.StrPacker private static final KEY_TS = `{"ts":`
    private static final String KEY_TS = "{\"ts\":";
    private static final long KEY_TS_W0 = 0x00003a227374227bL;
    private static final int KEY_TS_LEN = 6;
    private static final int KEY_TS_LEN_BUF = 8;

    // Fixed field prefixes (provenance: Apache Fory commit 585eb16f,
    // "feat(java): optimize json perf", PR #3871, Utf8WriterCodegen). Each prefix
    // is declared by a @CB.StrPacker marker below; CodeBuddy (project-automation)
    // rewrites the block into the naive String reference (stream fallback), the
    // 1-2 packed little-endian long words for the direct-buffer path (one 8-byte
    // VarHandle store per word instead of a virtual write(byte[]) call) and the
    // UTF-8 byte length, all as compile-time literals.

    // @CB.StrPacker private static final KEY_LEVEL = `"level":`
    private static final String KEY_LEVEL = "\"level\":";
    private static final long KEY_LEVEL_W0 = 0x3a226c6576656c22L;
    private static final int KEY_LEVEL_LEN = 8;
    private static final int KEY_LEVEL_LEN_BUF = 8;

    // @CB.StrPacker private static final KEY_LOGGER = `"logger":`
    private static final String KEY_LOGGER = "\"logger\":";
    private static final long KEY_LOGGER_W0 = 0x22726567676f6c22L;
    private static final long KEY_LOGGER_W1 = 0x000000000000003aL;
    private static final int KEY_LOGGER_LEN = 9;
    private static final int KEY_LOGGER_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_THREAD = `"thread":`
    private static final String KEY_THREAD = "\"thread\":";
    private static final long KEY_THREAD_W0 = 0x2264616572687422L;
    private static final long KEY_THREAD_W1 = 0x000000000000003aL;
    private static final int KEY_THREAD_LEN = 9;
    private static final int KEY_THREAD_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_MSG = `"msg":`
    private static final String KEY_MSG = "\"msg\":";
    private static final long KEY_MSG_W0 = 0x00003a2267736d22L;
    private static final int KEY_MSG_LEN = 6;
    private static final int KEY_MSG_LEN_BUF = 8;

    // @CB.StrPacker private static final KEY_ERR_CLASS = `"errClass":`
    private static final String KEY_ERR_CLASS = "\"errClass\":";
    private static final long KEY_ERR_CLASS_W0 = 0x73616c4372726522L;
    private static final long KEY_ERR_CLASS_W1 = 0x00000000003a2273L;
    private static final int KEY_ERR_CLASS_LEN = 11;
    private static final int KEY_ERR_CLASS_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_ERR_MESSAGE = `"errMessage":`
    private static final String KEY_ERR_MESSAGE = "\"errMessage\":";
    private static final long KEY_ERR_MESSAGE_W0 = 0x7373654d72726522L;
    private static final long KEY_ERR_MESSAGE_W1 = 0x0000003a22656761L;
    private static final int KEY_ERR_MESSAGE_LEN = 13;
    private static final int KEY_ERR_MESSAGE_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_ERR_HASH = `"errHash":`
    private static final String KEY_ERR_HASH = "\"errHash\":";
    private static final long KEY_ERR_HASH_W0 = 0x6873614872726522L;
    private static final long KEY_ERR_HASH_W1 = 0x0000000000003a22L;
    private static final int KEY_ERR_HASH_LEN = 10;
    private static final int KEY_ERR_HASH_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_STACK = `"stack":`
    private static final String KEY_STACK = "\"stack\":";
    private static final long KEY_STACK_W0 = 0x3a226b6361747322L;
    private static final int KEY_STACK_LEN = 8;
    private static final int KEY_STACK_LEN_BUF = 8;

    // @CB.StrPacker private static final JSON_NULL = `null`
    private static final String JSON_NULL = "null";
    private static final long JSON_NULL_W0 = 0x000000006c6c756eL;
    private static final int JSON_NULL_LEN = 4;
    private static final int JSON_NULL_LEN_BUF = 8;

    // @CB.StrPacker public static final JSON_TRUE = `true`
    public static final String JSON_TRUE = "true";
    public static final long JSON_TRUE_W0 = 0x0000000065757274L;
    public static final int JSON_TRUE_LEN = 4;
    public static final int JSON_TRUE_LEN_BUF = 8;

    // @CB.StrPacker private static final JSON_FALSE = `false`
    public static final String JSON_FALSE = "false";
    public static final long JSON_FALSE_W0 = 0x00000065736c6166L;
    public static final int JSON_FALSE_LEN = 5;
    public static final int JSON_FALSE_LEN_BUF = 8;

    /** Filter applied to stack trace frame class names during fingerprinting. Defaults to accepting all frames. */
    private Predicate<String> stackTraceFilter = null;

    /**
     * Reusable hasher for the single-pass stack-trace fingerprint, owned by this
     * writer like the number buffers below and passed as a parameter to the
     * single-pass methods (which reset it internally). No hidden ThreadLocal
     * state â€” the writer is {@link NotThreadSafe}, so an instance must not be
     * used from several threads at once, exactly like the number buffers.
     */
    private final Wyhash64.Streaming fingerprintStream = new Wyhash64.Streaming(0);

    public JsonLogWriter() {}

    /**
     * Sets the predicate used to decide which stack trace frames are included in the {@code errHash} fingerprint.
     * <p>
     * Only the class name of each frame is passed to the predicate. Frames that fail the test are excluded
     * from both the written {@code stack} field and the fingerprint.
     *
     * @param filter frame class filter; {@code null} resets to the default accept-all predicate
     */
    public void setStackTraceFilter(Predicate<String> filter) {
        this.stackTraceFilter = filter;
    }

    public Predicate<String> getStackTraceFilter() {
        return stackTraceFilter;
    }

    /**
     * Direct-buffer assembly (the production path). Callers that already hold a
     * {@link ReusableByteArrayOutputStream} must call this variant directly —
     * there is no OutputStream dispatcher that would route through the naive
     * stream path when the buffer is available.
     * <p>
     * T4 option 2: full "writer owns the buffer" assembly (ported from Apache
     * Fory commit 585eb16f, Utf8JsonWriter's getBuffer/getPosition/setPosition
     * design). One reusable {@link ReusableByteArrayOutputStream} cursor keeps {@code byte[]
     * buf} and {@code int pos} live for the whole event: fixed prefixes are
     * packed-long stores, strings are escaped straight into the buffer, numbers
     * are built and copied with one bulk write — all with inlined capacity
     * checks. Only stream-only delegations (jackson, raw values, the generated
     * stack-trace writers, dev {@code writeExtraFields}) publish the cursor,
     * write through the stream, then resync.
     */
    public void writeJsonEventDirect(ObjectMapper mapper, ILoggingEvent event, ReusableByteArrayOutputStream rbo) throws IOException {
        rbo.reset();
        byte[] buf = rbo.buf;
        int pos = 0;
        int limit = buf.length;
        // @CB.StrPackerWrite.config buffer=buf, position=pos, limit=limit

        // T7 caller-owns-cursor: '{' + "ts": + timestamp are one combined
        // capacity check + straight-line stores, keeping buf/pos/limit in
        // registers (see doc/perf-exploration/t7-cursor-locality-buffer-writer.md). The
        // packed prefix is reserved as whole 8-byte word slots (KEY_TS_LEN_BUF):
        // a 6-byte key still occupies one full word.
        if (pos + KEY_TS_LEN_BUF + JsonNumberWriter.MAX_LONG_BYTES > limit) {
            buf = rbo.grow(pos + KEY_TS_LEN_BUF + JsonNumberWriter.MAX_LONG_BYTES);
            limit = buf.length;
        }
        // timestamp field ts includes starting { for object: one full 8-byte
        // word store; the cursor advances by the 6-byte key length.
        WriteOps.LE_LONG.set(buf, pos, KEY_TS_W0);
        pos += KEY_TS_LEN;
        pos = JsonNumberWriter.writeLong(buf, pos, event.getTimeStamp());

        // Fixed string fields: the ',' + packed key prefix is stored inline
        // with its own range check (field names are static constants, so the
        // check is constant-foldable); the value is written separately through
        // the grow-capable string writer. Re-read buf/limit after each (grow
        // may reallocate).
        if (pos + 1 + KEY_LEVEL_LEN_BUF > limit) {
            buf = rbo.grow(pos + 1 + KEY_LEVEL_LEN_BUF);
            limit = buf.length;
        }
        buf[pos++] = ',';
        WriteOps.LE_LONG.set(buf, pos, KEY_LEVEL_W0);
        pos += 8;
        pos = writeStringDirect(rbo, pos, event.getLevel() != null ? event.getLevel().toString() : null);
        buf = rbo.buf;
        limit = buf.length;

        if (pos + 1 + KEY_LOGGER_LEN_BUF > limit) {
            buf = rbo.grow(pos + 1 + KEY_LOGGER_LEN_BUF);
            limit = buf.length;
        }
        buf[pos++] = ',';
        WriteOps.LE_LONG.set(buf, pos, KEY_LOGGER_W0);
        pos += 8;
        WriteOps.LE_LONG.set(buf, pos, KEY_LOGGER_W1); // tail: full 8-byte store
        pos += 1;                                      // advance by the 1-byte tail
        pos = writeStringDirect(rbo, pos, event.getLoggerName());
        buf = rbo.buf;
        limit = buf.length;

        if (pos + 1 + KEY_THREAD_LEN_BUF > limit) {
            buf = rbo.grow(pos + 1 + KEY_THREAD_LEN_BUF);
            limit = buf.length;
        }
        buf[pos++] = ',';
        WriteOps.LE_LONG.set(buf, pos, KEY_THREAD_W0);
        pos += 8;
        WriteOps.LE_LONG.set(buf, pos, KEY_THREAD_W1); // tail: full 8-byte store
        pos += 1;                                      // advance by the 1-byte tail
        pos = writeStringDirect(rbo, pos, event.getThreadName());
        buf = rbo.buf;
        limit = buf.length;

        if (pos + 1 + KEY_MSG_LEN_BUF > limit) {
            buf = rbo.grow(pos + 1 + KEY_MSG_LEN_BUF);
            limit = buf.length;
        }
        buf[pos++] = ',';
        WriteOps.LE_LONG.set(buf, pos, KEY_MSG_W0); // 6-byte key: full store, partial advance
        pos += KEY_MSG_LEN;
        pos = writeStringDirect(rbo, pos, event.getFormattedMessage());
        buf = rbo.buf;
        limit = buf.length;

        Map<String, String> mdcMap = null;
        try {
            mdcMap = event.getMDCPropertyMap();
        } catch (Exception ignored) {}

        // Structured key-value pairs. The caller keeps buf/pos/limit live across
        // the loop: ','/':' are inline stores; the variable-length key/value run
        // through the grow-capable helpers (publish + re-read after each).
        List<KeyValuePair> pairs = event.getKeyValuePairs();
        if (pairs != null && !pairs.isEmpty()) {
            for (KeyValuePair kvPair : pairs) {
                if (kvPair.key != null && kvPair.value != null) {
                    if (pos >= limit) {
                        buf = rbo.grow(pos + 1);
                        limit = buf.length;
                    }
                    buf[pos++] = ',';
                    pos = writeStringDirect(rbo, pos, kvPair.key);
                    buf = rbo.buf;
                    limit = buf.length;
                    if (pos >= limit) {
                        buf = rbo.grow(pos + 1);
                        limit = buf.length;
                    }
                    buf[pos++] = ':';
                    pos = writeValueDirect(rbo, pos, kvPair.value, mapper);
                    buf = rbo.buf;
                    limit = buf.length;
                }
            }
        }

        if (mdcMap != null && !mdcMap.isEmpty()) {
            for (Map.Entry<String, String> entry : mdcMap.entrySet()) {
                String key = entry.getKey();
                if (key != null && !isReserved(key)) {
                    if (pos >= limit) {
                        buf = rbo.grow(pos + 1);
                        limit = buf.length;
                    }
                    buf[pos++] = ',';
                    pos = writeStringDirect(rbo, pos, key);
                    buf = rbo.buf;
                    limit = buf.length;
                    if (pos >= limit) {
                        buf = rbo.grow(pos + 1);
                        limit = buf.length;
                    }
                    buf[pos++] = ':';
                    pos = writeStringDirect(rbo, pos, entry.getValue());
                    buf = rbo.buf;
                    limit = buf.length;
                }
            }
        }

        // Exception info
        IThrowableProxy tp = event.getThrowableProxy();
        if (tp != null) {
            String throwableClassName = tp.getClassName();
            String throwableMessage = tp.getMessage();

            // errClass: inline ',' + packed key prefix, value written separately.
            if (pos + 1 + KEY_ERR_CLASS_LEN_BUF > limit) {
                buf = rbo.grow(pos + 1 + KEY_ERR_CLASS_LEN_BUF);
                limit = buf.length;
            }
            buf[pos++] = ',';
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_CLASS_W0);
            pos += 8;
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_CLASS_W1); // tail: full 8-byte store
            pos += 3;                                         // advance by the 3-byte tail
            pos = writeStringDirect(rbo, pos, throwableClassName);
            buf = rbo.buf;
            limit = buf.length;

            // errMessage: inline ',' + packed key prefix, value written separately.
            if (pos + 1 + KEY_ERR_MESSAGE_LEN_BUF > limit) {
                buf = rbo.grow(pos + 1 + KEY_ERR_MESSAGE_LEN_BUF);
                limit = buf.length;
            }
            buf[pos++] = ',';
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_MESSAGE_W0);
            pos += 8;
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_MESSAGE_W1); // tail: full 8-byte store
            pos += 5;                                           // advance by the 5-byte tail
            pos = writeStringDirect(rbo, pos, throwableMessage);
            buf = rbo.buf;
            limit = buf.length;

            // The stack-trace writers are OutputStream-based (generated
            // sanitizer derivatives — see AGENTS.md); commit the cursor, write
            // the stack through the stream, then re-read.
            if (pos + 1 + KEY_STACK_LEN_BUF > limit) {
                buf = rbo.grow(pos + 1 + KEY_STACK_LEN_BUF);
                limit = buf.length;
            }
            buf[pos++] = ',';
            WriteOps.LE_LONG.set(buf, pos, KEY_STACK_W0);
            pos += 8;
            rbo.pos = pos;
            rbo.write('"');
            if (throwableClassName != null) {
                STRING_STRATEGY.write(rbo, throwableClassName);
            }
            StackTraceElementProxy[] arrProxy = tp.getStackTraceElementProxyArray();
            // Reuse this writer's hasher (owned like the number buffers) so
            // exception events allocate nothing â€” the single-pass methods
            // reset the stream internally.
            Wyhash64.Streaming stream = fingerprintStream;
            // micro optimization to call variant without filter
            long fingerPrint = stackTraceFilter == null ?
            JavaStackWriterLogback.addFromTraceToOutputStreamJsonAndFingerprint(
                arrProxy,
                rbo,
                throwableClassName,
                stream
            ) : 
            JavaStackSanitizerLogback.addFromTraceToOutputStreamJsonAndFingerprint(
                arrProxy,
                stackTraceFilter,
                rbo,
                throwableClassName,
                stream
            );
            rbo.write('"');
            rbo.resync();
            pos = rbo.pos;
            buf = rbo.buf;
            limit = buf.length;

            // errHash: inline prefix + bounded long (like ts); the prefix is
            // reserved as whole 8-byte word slots.
            if (pos + 1 + KEY_ERR_HASH_LEN_BUF + JsonNumberWriter.MAX_LONG_BYTES > limit) {
                buf = rbo.grow(pos + 1 + KEY_ERR_HASH_LEN_BUF + JsonNumberWriter.MAX_LONG_BYTES);
                limit = buf.length;
            }
            buf[pos++] = ',';
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_HASH_W0);
            pos += 8;
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_HASH_W1); // tail: full 8-byte store
            pos += 2;                                        // advance by the 2-byte tail
            pos = JsonNumberWriter.writeLong(buf, pos, fingerPrint);
        }

        // Dev/diagnostic extension point — OutputStream-based; commit + resync.
        rbo.pos = pos;
        rbo.publish();
        writeExtraFields(event, rbo, pairs, mdcMap);
        rbo.resync();
        pos = rbo.pos;
        buf = rbo.buf;
        limit = buf.length;

        // closing brace (inline)
        if (pos >= limit) {
            buf = rbo.grow(pos + 1);
        }
        buf[pos] = '}';
        rbo.pos = pos + 1;
    }

    /**
     * Extension point for diagnostic/dev writer variants (e.g. missing-key
     * warnings). Called after all regular fields but before the closing brace.
     * The default implementation writes nothing, so production output is
     * unaffected; implementations must write a complete field including its own
     * leading comma (like {@code writeFieldPrefix}) when they want to add data.
     *
     * @param event  the event being serialized
     * @param out    the target stream, positioned after the last regular field
     * @param pairs  the event's statement key/value pairs, or {@code null}
     * @param mdcMap MDC map, or {@code null} if none was available
     */
    protected void writeExtraFields(ILoggingEvent event, OutputStream out, List<KeyValuePair> pairs, Map<String, String> mdcMap) throws IOException {
        // no-op in the production writer
    }

    private boolean isReserved(String key) {
        return switch (key) {
            case "ts", "level", "logger", "thread", "msg", "errClass", "errHash", "errMessage" -> true;
            default -> false;
        };
    }

    /** Writes {@code ','} + the packed key's naive String form (stream fallback path only). */
    private static void writeFieldPrefix(OutputStream out, String key) throws IOException {
        out.write(',');
        out.write(key.getBytes(StandardCharsets.UTF_8));
    }

    private static void writeFieldPrefixRawKey(OutputStream out, String key) throws IOException {
        out.write(',');
        // Keys are user input â€” JSON-escape them (quotes, backslash, control chars).
        EscapedJsonStringWriter.writeJsonStringOrNull(out, key);
        out.write(':');
    }

    public static void writeRawValue(OutputStream out, RawValue raw, ObjectMapper mapper) throws IOException {
        Object backing = raw.rawValue();
        if (backing == null) {
            out.write(JSON_NULL.getBytes(StandardCharsets.UTF_8));
            return;
        }
        if (backing instanceof String s) {
            STRING_STRATEGY.write(out, s);
            return;
        }
        mapper.writeValue(out, raw);
    }

    private static void writeJsonStringOrNull(OutputStream out, String value) throws IOException {
        EscapedJsonStringWriter.writeJsonStringOrNull(out, value);
    }

    // =========================================================================
    // T4 option 2 — direct-buffer helpers
    // =========================================================================

    /** Commits the local cursor, writes a JSON string through rbo, returns the new position. */
    private static int writeStringDirect(ReusableByteArrayOutputStream rbo, int pos, String value) {
        rbo.pos = pos;
        return WriteOps.writeEscapedJsonString(rbo, value);
    }

    /**
     * Writes a JSON value straight into {@code rbo}, returning the advanced cursor.
     * The cursor {@code pos} is a primitive caller-owned local: the caller passes
     * it in and takes the new value back, so C2 keeps {@code pos} in a register
     * across the whole serialize sequence — see {@code
     * doc/perf-exploration/t7-cursor-locality-buffer-writer.md}. The grow-capable
     * backend helpers ({@code WriteOps}, {@code JsonNumberWriter}) still operate on
     * the {@code rbo.pos} field, so each branch commits the local cursor to the
     * field once (via {@code rbo.pos = pos}) before a grow/publish, then reads the
     * advanced value back — a single sync per value, not a field round-trip per
     * byte. Only the stream-mediated delegations (jackson, raw values,
     * self-writers) commit, write through the stream, resync, and return the new
     * {@code rbo.pos}.
     */
    private static int writeValueDirect(ReusableByteArrayOutputStream rbo, int pos, Object value, ObjectMapper mapper) throws IOException {
        switch (value) {
            case String s -> pos = writeEscapedJsonString(rbo, pos, s);
            case CharSequence cs -> pos = writeEscapedJsonString(rbo, pos, cs.toString());
            case Character ch -> pos = writeEscapedJsonString(rbo, pos, ch.toString());
            case Enum<?> e -> pos = writeEscapedJsonString(rbo, pos, e.name());
            case RawValue raw -> pos = writeRawValueDirect(rbo, pos, raw, mapper);
            case Long l -> pos = writeLongDirect(rbo, pos, l);
            case Integer i -> pos = writeIntDirect(rbo, pos, i);
            case Short s -> pos = writeIntDirect(rbo, pos, s.intValue());
            case Byte b -> pos = writeIntDirect(rbo, pos, b.intValue());
            case Float f -> pos = writeFloatDirect(rbo, pos, f);
            case Double d -> pos = writeDoubleDirect(rbo, pos, d);
            case Number n -> pos = writeNumberDirect(rbo, pos, n);
            case Boolean b -> {
                rbo.pos = pos;
                if (b) {
                    rbo.ensure(JSON_TRUE_LEN_BUF);
                    WriteOps.LE_LONG.set(rbo.buf, pos, JSON_TRUE_W0);
                    pos += JSON_TRUE_LEN;
                } else {
                    rbo.ensure(JSON_FALSE_LEN_BUF);
                    WriteOps.LE_LONG.set(rbo.buf, pos, JSON_FALSE_W0);
                    pos += JSON_FALSE_LEN;
                }
            }
            case RawJsonSelfWriter w -> {
                rbo.pos = pos;
                rbo.publish();
                w.writeJson(rbo);
                rbo.resync();
                pos = rbo.pos;
            }
            case RawJsonBytes b -> pos = writeRawJsonBytes(rbo, pos, b);
            default -> {
                rbo.pos = pos;
                rbo.publish();
                mapper.writeValue(rbo, value);
                rbo.resync();
                pos = rbo.pos;
            }
        }
        return pos;
    }

    /** Commits the local cursor, writes an escaped JSON string through rbo, returns the new position. */
    private static int writeEscapedJsonString(ReusableByteArrayOutputStream rbo, int pos, String value) {
        rbo.pos = pos;
        return WriteOps.writeEscapedJsonString(rbo, value);
    }

    /** Commits the local cursor, bulk-copies pre-encoded raw JSON bytes through rbo, returns the new position. */
    private static int writeRawJsonBytes(ReusableByteArrayOutputStream rbo, int pos, RawJsonBytes b) {
        rbo.pos = pos;
        return WriteOps.writeRaw(rbo, b.bytes(), 0, b.bytes().length);
    }

    private static int writeRawValueDirect(ReusableByteArrayOutputStream rbo, int pos, RawValue raw, ObjectMapper mapper) throws IOException {
        Object backing = raw.rawValue();
        if (backing == null) {
            rbo.pos = pos;
            rbo.ensure(JSON_NULL_LEN_BUF);
            WriteOps.LE_LONG.set(rbo.buf, pos, JSON_NULL_W0);
            pos += JSON_NULL_LEN;
            return pos;
        }
        rbo.pos = pos;
        rbo.publish();
        writeRawValue(rbo, raw, mapper);
        rbo.resync();
        return rbo.pos;
    }

    private static int writeNumberDirect(ReusableByteArrayOutputStream rbo, int pos, Number n) throws IOException {
        switch (n) {
            case Integer i -> pos = writeIntDirect(rbo, pos, i);
            case Long l -> pos = writeLongDirect(rbo, pos, l);
            case Short s -> pos = writeIntDirect(rbo, pos, s.intValue());
            case Byte b -> pos = writeIntDirect(rbo, pos, b.intValue());
            case Float f -> pos = writeFloatDirect(rbo, pos, f);
            case Double d -> pos = writeDoubleDirect(rbo, pos, d);
            default -> {
                rbo.pos = pos;
                rbo.publish();
                JsonNumberWriter.writeNumber(rbo, n);
                rbo.resync();
                pos = rbo.pos;
            }
        }
        return pos;
    }

    private static int writeIntDirect(ReusableByteArrayOutputStream rbo, int pos, int value) {
        rbo.pos = pos;
        rbo.ensure(JsonNumberWriter.MAX_INT_BYTES);
        return JsonNumberWriter.writeInt(rbo.buf, pos, value);
    }

    private static int writeLongDirect(ReusableByteArrayOutputStream rbo, int pos, long value) {
        rbo.pos = pos;
        rbo.ensure(JsonNumberWriter.MAX_LONG_BYTES);
        return JsonNumberWriter.writeLong(rbo.buf, pos, value);
    }

    private static int writeFloatDirect(ReusableByteArrayOutputStream rbo, int pos, float value) {
        rbo.pos = pos;
        rbo.ensure(JsonNumberWriter.MAX_FLOAT_BYTES);
        return JsonNumberWriter.writeFloat(rbo.buf, pos, value);
    }

    private static int writeDoubleDirect(ReusableByteArrayOutputStream rbo, int pos, double value) {
        rbo.pos = pos;
        rbo.ensure(JsonNumberWriter.MAX_DOUBLE_BYTES);
        return JsonNumberWriter.writeDouble(rbo.buf, pos, value);
    }

    /** Packs up to 8 bytes starting at {@code off} little-endian into one long. */
    private static long packWord(byte[] bytes, int off) {
        long v = 0;
        int end = Math.min(off + 8, bytes.length);
        for (int i = off; i < end; i++) {
            v |= (bytes[i] & 0xFFL) << ((i - off) << 3);
        }
        return v;
    }
}
