package hr.hrg.dialog.logback;

import javax.annotation.concurrent.NotThreadSafe;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;

import ch.qos.logback.classic.spi.StackTraceElementProxy;
import hr.hrg.dialog.core.*;
import org.slf4j.event.KeyValuePair;

import tools.jackson.core.JacksonException;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.util.RawValue;

import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.spi.IThrowableProxy;

/// Reusable JSON log event writer used internally.
///
/// It tries to minimize allocations
/// - if add-opens available, uses direct string data access to avoid allocating byte[] for each string
/// - holds byte[] for common keys, to again avoid allocation byte[] caused by writing string in Java
/// - delegates custom key/value and MDC to jackson
/// - writes stack trace into JSON with optimized low allocation code
///
@NotThreadSafe
public class JsonLogWriter {

    /** Newline byte (UTF-8) - strictly Unix LF (\n). */
    public static final byte NL = 0x0A;

    /**
     * A value whose JSON representation has already been computed and encoded
     * to UTF-8 bytes.
     *
     * <p>This is a <b>trusted passthrough</b>: the bytes are injected into the
     * output stream verbatim — no escaping, no quoting, no validation. The
     * caller owns correctness of the payload; malformed content will corrupt
     * the surrounding JSON object.
     *
     * <p>Use it for values that are serialized once and reused across many
     * events, so the per-event cost is a single bulk byte copy instead of a
     * re-serialization. Example — a large, rarely-changing configuration or
     * metrics snapshot cached as pre-encoded bytes:
     *
     * <pre>{@code
     * // computed once, reused across many log lines
     * byte[] snapshotJson = mapper.writeValueAsBytes(configSnapshot);
     * ...
     * List.of(new KeyValuePair("config", new JsonLogWriter.RawJsonBytes(snapshotJson)))
     * }</pre>
     *
     * @param bytes the pre-encoded JSON fragment, written verbatim
     */
    public record RawJsonBytes(byte[] bytes){}

    public static final StringByteExtractor.ByteWriter STRING_STRATEGY = StringByteExtractor.getStrategy();

    // timestamp field ts includes starting { for object, and is generated by CodeBuddy StrPacker from project-automation
    // @CB.StrPacker private static final KEY_TS = `{"ts":`
    private static final String KEY_TS = "{\"ts\":";
    private static final long KEY_TS_W0 = 0x00003a227374227bL;
    private static final int KEY_TS_LEN = 6;
    private static final int KEY_TS_LEN_BUF = 8;

    // Fixed field prefixes (provenance: Apache Fory commit 585eb16f,
    // "feat(java): optimize json perf", PR #3871, Utf8WriterCodegen). Each prefix
    // is declared by a @CB.StrPacker marker below; CodeBuddy (project-automation)
    // rewrites the block into the naive String reference (stream fallback), the
    // 1-2 packed little-endian long words for the direct-buffer path (one 8-byte
    // VarHandle store per word instead of a virtual write(byte[]) call) and the
    // UTF-8 byte length, all as compile-time literals.

    // @CB.StrPacker private static final KEY_LEVEL = `"level":`
    private static final String KEY_LEVEL = "\"level\":";
    private static final long KEY_LEVEL_W0 = 0x3a226c6576656c22L;
    private static final int KEY_LEVEL_LEN = 8;
    private static final int KEY_LEVEL_LEN_BUF = 8;

    // @CB.StrPacker private static final KEY_LOGGER = `"logger":`
    private static final String KEY_LOGGER = "\"logger\":";
    private static final long KEY_LOGGER_W0 = 0x22726567676f6c22L;
    private static final long KEY_LOGGER_W1 = 0x000000000000003aL;
    private static final int KEY_LOGGER_LEN = 9;
    private static final int KEY_LOGGER_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_THREAD = `"thread":`
    private static final String KEY_THREAD = "\"thread\":";
    private static final long KEY_THREAD_W0 = 0x2264616572687422L;
    private static final long KEY_THREAD_W1 = 0x000000000000003aL;
    private static final int KEY_THREAD_LEN = 9;
    private static final int KEY_THREAD_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_MSG = `"msg":`
    private static final String KEY_MSG = "\"msg\":";
    private static final long KEY_MSG_W0 = 0x00003a2267736d22L;
    private static final int KEY_MSG_LEN = 6;
    private static final int KEY_MSG_LEN_BUF = 8;

    // @CB.StrPacker private static final KEY_ERR_CLASS = `"errClass":`
    private static final String KEY_ERR_CLASS = "\"errClass\":";
    private static final long KEY_ERR_CLASS_W0 = 0x73616c4372726522L;
    private static final long KEY_ERR_CLASS_W1 = 0x00000000003a2273L;
    private static final int KEY_ERR_CLASS_LEN = 11;
    private static final int KEY_ERR_CLASS_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_ERR_MESSAGE = `"errMessage":`
    private static final String KEY_ERR_MESSAGE = "\"errMessage\":";
    private static final long KEY_ERR_MESSAGE_W0 = 0x7373654d72726522L;
    private static final long KEY_ERR_MESSAGE_W1 = 0x0000003a22656761L;
    private static final int KEY_ERR_MESSAGE_LEN = 13;
    private static final int KEY_ERR_MESSAGE_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_ERR_HASH = `"errHash":`
    private static final String KEY_ERR_HASH = "\"errHash\":";
    private static final long KEY_ERR_HASH_W0 = 0x6873614872726522L;
    private static final long KEY_ERR_HASH_W1 = 0x0000000000003a22L;
    private static final int KEY_ERR_HASH_LEN = 10;
    private static final int KEY_ERR_HASH_LEN_BUF = 16;

    // @CB.StrPacker private static final KEY_STACK = `"stack":`
    private static final String KEY_STACK = "\"stack\":";
    private static final long KEY_STACK_W0 = 0x3a226b6361747322L;
    private static final int KEY_STACK_LEN = 8;
    private static final int KEY_STACK_LEN_BUF = 8;

    // @CB.StrPacker private static final JSON_NULL = `null`
    public static final String JSON_NULL = "null";
    private static final long JSON_NULL_W0 = 0x000000006c6c756eL;
    private static final int JSON_NULL_LEN = 4;
    private static final int JSON_NULL_LEN_BUF = 8;

    // @CB.StrPacker public static final JSON_TRUE = `true`
    public static final String JSON_TRUE = "true";
    public static final long JSON_TRUE_W0 = 0x0000000065757274L;
    public static final int JSON_TRUE_LEN = 4;
    public static final int JSON_TRUE_LEN_BUF = 8;

    // @CB.StrPacker public static final JSON_FALSE = `false`
    public static final String JSON_FALSE = "false";
    public static final long JSON_FALSE_W0 = 0x00000065736c6166L;
    public static final int JSON_FALSE_LEN = 5;
    public static final int JSON_FALSE_LEN_BUF = 8;

    /// Tail reserve for the no-grow event assembly (T12):
    /// JsonNumberWriter.MAX_DOUBLE_BYTES (25) + '}' (1) + '\n' (1) = 27.
    /// `limit = buf.length - RESERVE` is the hard boundary the limit-aware
    /// writers check against, so the closing '}' and the appender's newline
    /// always fit in the reserved tail. RESERVE also exceeds the "V2BIG"
    /// placeholder length (7), so a placeholder and any number both fit.
    private static final int RESERVE = JsonNumberWriter.MAX_DOUBLE_BYTES + 2;

    // @CB.StrPacker private static final PLACEHOLDER = `"V2BIG"`
    private static final long PLACEHOLDER_W0 = 0x0022474942325622L; // "V2BIG"
    private static final int PLACEHOLDER_LEN = 7;

    /** Filter applied to stack trace frame class names during fingerprinting. Defaults to accepting all frames. */
    private Predicate<String> stackTraceFilter = null;

    /**
     * Reusable hasher for the single-pass stack-trace fingerprint, owned by this
     * writer like the number buffers below and passed as a parameter to the
     * single-pass methods (which reset it internally). No hidden ThreadLocal
     * state â€” the writer is {@link NotThreadSafe}, so an instance must not be
     * used from several threads at once, exactly like the number buffers.
     */
    private final Wyhash64.Streaming fingerprintStream = new Wyhash64.Streaming(0);

    public JsonLogWriter() {}

    /**
     * Sets the predicate used to decide which stack trace frames are included in the {@code errHash} fingerprint.
     * <p>
     * Only the class name of each frame is passed to the predicate. Frames that fail the test are excluded
     * from both the written {@code stack} field and the fingerprint.
     *
     * @param filter frame class filter; {@code null} resets to the default accept-all predicate
     */
    public void setStackTraceFilter(Predicate<String> filter) {
        this.stackTraceFilter = filter;
    }

    public Predicate<String> getStackTraceFilter() {
        return stackTraceFilter;
    }

    /**
     * Direct-buffer assembly (the production path). Callers that already hold a
     * {@link ReusableByteArrayOutputStream} must call this variant directly —
     * there is no OutputStream dispatcher that would route through the naive
     * stream path when the buffer is available.
     * <p>
     * T4 option 2: full "writer owns the buffer" assembly (ported from Apache
     * Fory commit 585eb16f, Utf8JsonWriter's getBuffer/getPosition/setPosition
     * design). One reusable {@link ReusableByteArrayOutputStream} cursor keeps {@code byte[]
     * buf} and {@code int pos} live for the whole event: fixed prefixes are
     * packed-long stores, strings are escaped straight into the buffer, numbers
     * are built and copied with one bulk write — all with inlined capacity
     * checks against the stable {@code limit = buf.length - RESERVE}.
     * <p>
     * The buffer is fixed-capacity (no-grow, see T12): a value that overflows
     * is replaced by the packed {@code "V2BIG"} literal and the object stays
     * open for subsequent fields; a field key that no longer fits closes the
     * object with {@code '}'}, leaving the already-written fields valid JSON.
     * Only stream-only delegations (jackson, raw values, the generated
     * stack-trace writers) commit the cursor and write through the stream.
     * <p>
     * The caller resets the buffer before calling and stores the returned
     * position into {@code rbo.pos}; this method starts at {@code pos = 0}.
     *
     * @return the position after the closing {@code '}'}
     */
    public int writeJsonEventDirect(ObjectMapper mapper, ILoggingEvent event, ReusableByteArrayOutputStream rbo) throws IOException {
        byte[] buf = rbo.buf;
        int pos = 0;
        int limit = buf.length - RESERVE;
        // @CB.StrPackerWrite.config buffer=buf, position=pos, limit=limit

        // T7 caller-owns-cursor: '{' + "ts": + timestamp are one combined
        // capacity check + straight-line stores, keeping buf/pos/limit in
        // registers (see doc/perf-exploration/t7-cursor-locality-buffer-writer.md). The
        // packed prefix is reserved as whole 8-byte word slots (KEY_TS_LEN_BUF):
        // a 6-byte key still occupies one full word.
        if (pos + KEY_TS_LEN_BUF + JsonNumberWriter.MAX_LONG_BYTES > limit) {
            // Unreachable at the 64-byte minimum (limit >= 37 > 0 + 8 + 20 = 28);
            // defensive only. If it ever fired at pos == 0, emit a minimal "{}".
            buf[pos] = '{';
            buf[pos + 1] = '}';
            return pos + 2;
        }
        // timestamp field ts includes starting { for object: one full 8-byte
        // word store; the cursor advances by the 6-byte key length.
        WriteOps.LE_LONG.set(buf, pos, KEY_TS_W0);
        pos += KEY_TS_LEN;
        pos = JsonNumberWriter.writeLong(buf, pos, event.getTimeStamp());

        // Fixed string fields: the ',' + packed key prefix is stored inline
        // with its own range check (field names are static constants, so the
        // check is constant-foldable); the value is written separately through
        // the limit-aware string writer. A key that no longer fits closes the
        // object (writeTooLargeAndClose); a value overflow writes "V2BIG"
        // (writeTooLargeField) and the loop continues with the next field.
        if (pos + 1 + KEY_LEVEL_LEN_BUF > limit) {
            return writeTooLargeAndClose(buf, pos);
        }
        buf[pos++] = ',';
        WriteOps.LE_LONG.set(buf, pos, KEY_LEVEL_W0);
        pos += 8;
        pos = writeEscapedJsonString(buf, pos, limit,
                event.getLevel() != null ? event.getLevel().toString() : null);
        if (pos < 0) {
            pos = writeTooLargeField(buf, -pos);
        }

        if (pos + 1 + KEY_LOGGER_LEN_BUF > limit) {
            return writeTooLargeAndClose(buf, pos);
        }
        buf[pos++] = ',';
        WriteOps.LE_LONG.set(buf, pos, KEY_LOGGER_W0);
        pos += 8;
        WriteOps.LE_LONG.set(buf, pos, KEY_LOGGER_W1); // tail: full 8-byte store
        pos += 1;                                      // advance by the 1-byte tail
        pos = writeEscapedJsonString(buf, pos, limit, event.getLoggerName());
        if (pos < 0) {
            pos = writeTooLargeField(buf, -pos);
        }

        if (pos + 1 + KEY_THREAD_LEN_BUF > limit) {
            return writeTooLargeAndClose(buf, pos);
        }
        buf[pos++] = ',';
        WriteOps.LE_LONG.set(buf, pos, KEY_THREAD_W0);
        pos += 8;
        WriteOps.LE_LONG.set(buf, pos, KEY_THREAD_W1); // tail: full 8-byte store
        pos += 1;                                      // advance by the 1-byte tail
        pos = writeEscapedJsonString(buf, pos, limit, event.getThreadName());
        if (pos < 0) {
            pos = writeTooLargeField(buf, -pos);
        }

        if (pos + 1 + KEY_MSG_LEN_BUF > limit) {
            return writeTooLargeAndClose(buf, pos);
        }
        buf[pos++] = ',';
        WriteOps.LE_LONG.set(buf, pos, KEY_MSG_W0); // 6-byte key: full store, partial advance
        pos += KEY_MSG_LEN;
        pos = writeEscapedJsonString(buf, pos, limit, event.getFormattedMessage());
        if (pos < 0) {
            pos = writeTooLargeField(buf, -pos);
        }

        Map<String, String> mdcMap = null;
        try {
            mdcMap = event.getMDCPropertyMap();
        } catch (Exception ignored) {}

        // Structured key-value pairs. The caller keeps buf/pos/limit live across
        // the loop. Keys are user input and variable-length: ',' + key + ':' is
        // written through the limit-aware escaped writer; a key that no longer
        // fits restores to before the ',' and closes the object, a value
        // overflow writes "V2BIG" and the loop continues.
        List<KeyValuePair> pairs = event.getKeyValuePairs();
        if (pairs != null && !pairs.isEmpty()) {
            for (KeyValuePair kvPair : pairs) {
                if (kvPair.key != null && kvPair.value != null) {
                    int fieldStart = pos;                   // before the ','
                    if (pos >= limit) {
                        return writeTooLargeAndClose(buf, fieldStart);
                    }
                    buf[pos++] = ',';
                    pos = writeEscapedJsonString(buf, pos, limit, kvPair.key);
                    if (pos < 0) {
                        return writeTooLargeAndClose(buf, fieldStart);
                    }
                    if (pos >= limit) {
                        return writeTooLargeAndClose(buf, fieldStart);
                    }
                    buf[pos++] = ':';
                    pos = writeValueDirect(buf, pos, limit, rbo, kvPair.value, mapper);
                    if (pos < 0) {
                        pos = writeTooLargeField(buf, -pos);   // "V2BIG" — stays open
                    }
                }
            }
        }

        if (mdcMap != null && !mdcMap.isEmpty()) {
            for (Map.Entry<String, String> entry : mdcMap.entrySet()) {
                String key = entry.getKey();
                if (key != null && !isReserved(key)) {
                    int fieldStart = pos;                   // before the ','
                    if (pos >= limit) {
                        return writeTooLargeAndClose(buf, fieldStart);
                    }
                    buf[pos++] = ',';
                    pos = writeEscapedJsonString(buf, pos, limit, key);
                    if (pos < 0) {
                        return writeTooLargeAndClose(buf, fieldStart);
                    }
                    if (pos >= limit) {
                        return writeTooLargeAndClose(buf, fieldStart);
                    }
                    buf[pos++] = ':';
                    pos = writeEscapedJsonString(buf, pos, limit, entry.getValue());
                    if (pos < 0) {
                        pos = writeTooLargeField(buf, -pos);   // "V2BIG" — stays open
                    }
                }
            }
        }

        // Exception info
        IThrowableProxy tp = event.getThrowableProxy();
        if (tp != null) {
            String throwableClassName = tp.getClassName();
            String throwableMessage = tp.getMessage();

            // errClass: inline ',' + packed key prefix, value written separately.
            if (pos + 1 + KEY_ERR_CLASS_LEN_BUF > limit) {
                return writeTooLargeAndClose(buf, pos);
            }
            buf[pos++] = ',';
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_CLASS_W0);
            pos += 8;
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_CLASS_W1); // tail: full 8-byte store
            pos += 3;                                         // advance by the 3-byte tail
            pos = writeEscapedJsonString(buf, pos, limit, throwableClassName);
            if (pos < 0) {
                pos = writeTooLargeField(buf, -pos);
            }

            // errMessage: inline ',' + packed key prefix, value written separately.
            if (pos + 1 + KEY_ERR_MESSAGE_LEN_BUF > limit) {
                return writeTooLargeAndClose(buf, pos);
            }
            buf[pos++] = ',';
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_MESSAGE_W0);
            pos += 8;
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_MESSAGE_W1); // tail: full 8-byte store
            pos += 5;                                           // advance by the 5-byte tail
            pos = writeEscapedJsonString(buf, pos, limit, throwableMessage);
            if (pos < 0) {
                pos = writeTooLargeField(buf, -pos);
            }

            // The stack-trace writers are OutputStream-based (generated
            // sanitizer derivatives — see AGENTS.md); commit the cursor and
            // write the stack through the stream. The no-grow RBO write methods
            // throw BufferFullException at buf.length; a thrown or reserve-
            // overrunning stack is replaced by "V2BIG" for the whole field.
            if (pos + 1 + KEY_STACK_LEN_BUF > limit) {
                return writeTooLargeAndClose(buf, pos);
            }
            buf[pos++] = ',';
            WriteOps.LE_LONG.set(buf, pos, KEY_STACK_W0);
            pos += 8;
            int stackFieldStart = pos;          // position of the stack VALUE
            long fingerPrint = 0L;
            rbo.pos = pos;
            try {
                rbo.write('"');
                if (throwableClassName != null) {
                    STRING_STRATEGY.write(rbo, throwableClassName);
                }
                StackTraceElementProxy[] arrProxy = tp.getStackTraceElementProxyArray();
                // Reuse this writer's hasher (owned like the number buffers) so
                // exception events allocate nothing — the single-pass methods
                // reset the stream internally.
                Wyhash64.Streaming stream = fingerprintStream;
                // micro optimization to call variant without filter
                fingerPrint = stackTraceFilter == null ?
                JavaStackWriterLogback.addFromTraceToOutputStreamJsonAndFingerprint(
                    arrProxy,
                    rbo,
                    throwableClassName,
                    stream
                ) :
                JavaStackSanitizerLogback.addFromTraceToOutputStreamJsonAndFingerprint(
                    arrProxy,
                    stackTraceFilter,
                    rbo,
                    throwableClassName,
                    stream
                );
                rbo.write('"');
                pos = rbo.pos;
            } catch (BufferFullException e) {
                // The stack trace exceeded the fixed buffer: replace the whole
                // value with "V2BIG" — no '}', the object stays open.
                pos = writeTooLargeField(buf, stackFieldStart);
            }
            if (pos > limit) {
                // The stack writers throw only at rbo.buf.length, not at the
                // event limit — a stack that fits the buffer but overruns the
                // reserve is also treated as overflow.
                pos = writeTooLargeField(buf, stackFieldStart);
            }

            // errHash: inline prefix + bounded long (like ts); the prefix is
            // reserved as whole 8-byte word slots.
            if (pos + 1 + KEY_ERR_HASH_LEN_BUF + JsonNumberWriter.MAX_LONG_BYTES > limit) {
                return writeTooLargeAndClose(buf, pos);
            }
            buf[pos++] = ',';
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_HASH_W0);
            pos += 8;
            WriteOps.LE_LONG.set(buf, pos, KEY_ERR_HASH_W1); // tail: full 8-byte store
            pos += 2;                                        // advance by the 2-byte tail
            pos = JsonNumberWriter.writeLong(buf, pos, fingerPrint);
        }

        // Dev/diagnostic extension point — direct-buffer; returns the new
        // position, or the negated field-start on overflow (the caller
        // restores to before the partial field and closes with '}').
        int extraPos = writeExtraFields(event, buf, pos, limit, pairs, mdcMap);
        if (extraPos < 0) {
            pos = -extraPos;
            pos = writeTooLargeAndClose(buf, pos);
        } else {
            pos = extraPos;
        }

        // closing brace — RESERVE guarantees room
        buf[pos] = '}';
        return pos + 1;
    }

    /** Writes {@code '}'} (closes the object). Used when a {@code ','} + key
     *  prefix no longer fits; the previous field is already complete, so
     *  closing is valid. The caller guarantees room (pos <= buf.length - 1). */
    private static int writeTooLargeAndClose(byte[] buf, int pos) {
        buf[pos] = '}';
        return pos + 1;
    }

    /// Writes the packed "V2BIG" placeholder (7 bytes) without closing the
    /// object. Used when a value overflows but its key prefix was already
    /// written — subsequent fields can continue. The caller guarantees the
    /// placeholder fits (the value start is <= limit, and RESERVE = 27 > 7),
    /// so no capacity check is needed here.
    private static int writeTooLargeField(byte[] buf, int pos) {
        WriteOps.LE_LONG.set(buf, pos, PLACEHOLDER_W0);
        return pos + PLACEHOLDER_LEN;
    }

    /**
     * Extension point for diagnostic/dev writer variants (e.g. missing-key
     * warnings). Called after all regular fields but before the closing brace.
     * The default implementation writes nothing, so production output is
     * unaffected; implementations must write a complete field including its own
     * leading comma when they want to add data.
     * <p>
     * Returns the new position, or the negated field-start ({@code -pos}, the
     * position before the leading comma) on overflow — the caller restores and
     * closes the object with {@code '}'}, dropping the partial field cleanly.
     *
     * @param event  the event being serialized
     * @param buf    the event buffer
     * @param pos    the cursor, after the last regular field
     * @param limit  the hard boundary ({@code buf.length - RESERVE})
     * @param pairs  the event's statement key/value pairs, or {@code null}
     * @param mdcMap MDC map, or {@code null} if none was available
     * @return the new position, or {@code -pos} on overflow
     */
    protected int writeExtraFields(ILoggingEvent event, byte[] buf, int pos, int limit,
            List<KeyValuePair> pairs, Map<String, String> mdcMap) {
        return pos;  // no-op
    }

    private boolean isReserved(String key) {
        return switch (key) {
            case "ts", "level", "logger", "thread", "msg", "errClass", "errHash", "errMessage" -> true;
            default -> false;
        };
    }

    // =========================================================================
    // T4 option 2 — direct-buffer helpers
    // =========================================================================

    /**
     * Writes a JSON value straight into {@code buf[pos..limit)}, returning the
     * advanced cursor. The cursor {@code pos} is a primitive caller-owned local:
     * the caller passes it in and takes the new value back, so C2 keeps {@code
     * pos} in a register across the whole serialize sequence — see {@code
     * doc/perf-exploration/t7-cursor-locality-buffer-writer.md}. Scalar branches
     * write directly into {@code buf} with an inlined capacity check against
     * {@code limit} and return {@code -pos} on overflow; the stream-mediated
     * delegations (jackson, raw values, self-writers) commit the local cursor to
     * {@code rbo.pos}, write through the no-grow stream, and return
     * {@code -valueStart} on {@link BufferFullException} or when the write lands
     * past {@code limit}. The caller finalizes: {@code "V2BIG"} (field loop) or
     * a close with {@code '}'}.
     */
    private static int writeValueDirect(byte[] buf, int pos, int limit,
            ReusableByteArrayOutputStream rbo, Object value, ObjectMapper mapper) throws IOException {
        switch (value) {
            case String s -> pos = writeEscapedJsonString(buf, pos, limit, s);
            case CharSequence cs -> pos = writeEscapedJsonString(buf, pos, limit, cs.toString());
            case Character ch -> pos = writeEscapedJsonString(buf, pos, limit, ch.toString());
            case Enum<?> e -> pos = writeEscapedJsonString(buf, pos, limit, e.name());
            case Long l -> pos = writeLongDirect(buf, pos, limit, l);
            case Integer i -> pos = writeIntDirect(buf, pos, limit, i);
            case Short s -> pos = writeIntDirect(buf, pos, limit, s.intValue());
            case Byte b -> pos = writeIntDirect(buf, pos, limit, b.intValue());
            case Float f -> pos = writeFloatDirect(buf, pos, limit, f);
            case Double d -> pos = writeDoubleDirect(buf, pos, limit, d);
            case Number n -> pos = writeNumberDirect(buf, pos, limit, rbo, n);
            case Boolean b -> {
                if (b) {
                    if (pos + JSON_TRUE_LEN_BUF > limit) return -pos;
                    WriteOps.LE_LONG.set(buf, pos, JSON_TRUE_W0);
                    pos += JSON_TRUE_LEN;
                } else {
                    if (pos + JSON_FALSE_LEN_BUF > limit) return -pos;
                    WriteOps.LE_LONG.set(buf, pos, JSON_FALSE_W0);
                    pos += JSON_FALSE_LEN;
                }
            }
            case RawJsonSelfWriter w -> {
                int valueStart = pos;
                rbo.pos = pos;
                try {
                    w.writeJson(rbo);
                    pos = rbo.pos;
                } catch (BufferFullException e) {
                    return -valueStart;
                }
                if (pos > limit) return -valueStart;   // wrote into the reserve
            }
            case RawJsonBytes b -> pos = writeRawJsonBytes(buf, pos, limit, b);
            default -> {
                // jackson 3 wraps the no-grow BufferFullException in its own
                // unchecked exception (JacksonException / DatabindException), so
                // the catch must cover both: an unsized value that cannot be
                // written is replaced by "V2BIG".
                int valueStart = pos;
                rbo.pos = pos;
                try {
                    mapper.writeValue(rbo, value);
                    pos = rbo.pos;
                } catch (JacksonException | BufferFullException e) {
                    return -valueStart;
                }
                if (pos > limit) return -valueStart;    // wrote into the reserve
            }
        }
        return pos;
    }

    /** Writes an escaped JSON string into {@code buf[pos..limit)}, returns the
     *  new position, or {@code -pos} on overflow (the caller restores and
     *  finalizes). */
    private static int writeEscapedJsonString(byte[] buf, int pos, int limit, String value) {
        return WriteOps.writeEscapedJsonStringNoGrow(buf, pos, limit, value);
    }

    /** Bulk-copies pre-encoded raw JSON bytes into {@code buf[pos..limit)};
     *  returns the new position, or {@code -pos} on overflow. */
    private static int writeRawJsonBytes(byte[] buf, int pos, int limit, RawJsonBytes b) {
        return WriteOps.writeRawNoGrow(buf, pos, limit, b.bytes(), 0, b.bytes().length);
    }

    /** Arbitrary {@link Number} → stream-mediated through {@code rbo}; the
     *  wrapper types are caught by the caller's dispatch. Returns the new
     *  position, or {@code -valueStart} on overflow. */
    private static int writeNumberDirect(byte[] buf, int pos, int limit,
            ReusableByteArrayOutputStream rbo, Number n) throws IOException {
        switch (n) {
            case Integer i -> pos = writeIntDirect(buf, pos, limit, i);
            case Long l -> pos = writeLongDirect(buf, pos, limit, l);
            case Short s -> pos = writeIntDirect(buf, pos, limit, s.intValue());
            case Byte b -> pos = writeIntDirect(buf, pos, limit, b.intValue());
            case Float f -> pos = writeFloatDirect(buf, pos, limit, f);
            case Double d -> pos = writeDoubleDirect(buf, pos, limit, d);
            default -> {
                int valueStart = pos;
                rbo.pos = pos;
                try {
                    JsonNumberWriter.writeNumber(rbo, n);
                    pos = rbo.pos;
                } catch (BufferFullException e) {
                    return -valueStart;
                }
                if (pos > limit) return -valueStart;    // wrote into the reserve
            }
        }
        return pos;
    }

    private static int writeIntDirect(byte[] buf, int pos, int limit, int value) {
        if (pos + JsonNumberWriter.MAX_INT_BYTES > limit) return -pos;
        return JsonNumberWriter.writeInt(buf, pos, value);
    }

    private static int writeLongDirect(byte[] buf, int pos, int limit, long value) {
        if (pos + JsonNumberWriter.MAX_LONG_BYTES > limit) return -pos;
        return JsonNumberWriter.writeLong(buf, pos, value);
    }

    private static int writeFloatDirect(byte[] buf, int pos, int limit, float value) {
        if (pos + JsonNumberWriter.MAX_FLOAT_BYTES > limit) return -pos;
        return JsonNumberWriter.writeFloat(buf, pos, value);
    }

    private static int writeDoubleDirect(byte[] buf, int pos, int limit, double value) {
        if (pos + JsonNumberWriter.MAX_DOUBLE_BYTES > limit) return -pos;
        return JsonNumberWriter.writeDouble(buf, pos, value);
    }

    /** Packs up to 8 bytes starting at {@code off} little-endian into one long. */
    private static long packWord(byte[] bytes, int off) {
        long v = 0;
        int end = Math.min(off + 8, bytes.length);
        for (int i = off; i < end; i++) {
            v |= (bytes[i] & 0xFFL) << ((i - off) << 3);
        }
        return v;
    }
}
